name: rapporto_servizio
description: App rapporto di fine servizio
version: 1.0.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  pdf: ^3.10.6
  printing: ^5.12.0
  share_plus: ^12.0.1
  path_provider: ^2.1.2
  open_file: ^3.2.1
  image_picker: ^1.0.4
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
