const List<String> availableCronometristi = [
  'Angioletti Leo',
  'Bardea Federico',
  'Bardea Matteo',
  'Bardea Serafino',
  'Berni Elisa',
  'Bonomi Stefania',
  'Carugo Andrea',
  'Cavanna Nicoletta',
  'Dei Cas Marco',
  'Del Curto Sebastiano',
  "Dell'Olio Cosimo",
  'Giacomelli Fausto',
  'Marconi Luca',
  'Nana Fabiano',
  'Nani Stefano',
  'Osmetti Giulia',
  'Patroni Giovanni',
  'Romeri Roberta',
  'Romeri Stefano',
  'Ruffoni Fulvia',
  'Ruffoni Nicola',
  'Ruttico Flavio',
  'Santolini Riccardo',
  'Tarabini Alessandra',
  'Tognoli Jacopo',
  'Tognoli Mattia',
  'Tognoli Stefano',
  'Zanella Aurelio',
  'Zubiani Lucio',
  'Altra Associazione',
];
